-- Starter categories/accounts are now seeded automatically per-user by the
-- handle_new_user() trigger in schema.sql (each signup gets its own personal
-- copy), since these lists are no longer shared across users. Nothing to run
-- here manually anymore -- this file is kept only for historical reference.
