import {
  ArrowLeftRight,
  Award,
  Baby,
  Briefcase,
  Building2,
  Car,
  CircleHelp,
  Clapperboard,
  Coffee,
  Dumbbell,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  Laptop,
  PawPrint,
  Percent,
  Plane,
  Receipt,
  Repeat,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Undo2,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react'
import { categoryIconKey, type CategoryIconKey } from '@/lib/categoryIcon'

const ICONS: Record<CategoryIconKey, LucideIcon> = {
  home: Home,
  bolt: Zap,
  basket: ShoppingBasket,
  dining: UtensilsCrossed,
  car: Car,
  bag: ShoppingBag,
  health: HeartPulse,
  shield: ShieldCheck,
  film: Clapperboard,
  repeat: Repeat,
  education: GraduationCap,
  plane: Plane,
  sparkles: Sparkles,
  gift: Gift,
  receipt: Receipt,
  salary: Briefcase,
  laptop: Laptop,
  percent: Percent,
  trending: TrendingUp,
  building: Building2,
  award: Award,
  refund: Undo2,
  wallet: Wallet,
  review: CircleHelp,
  transfer: ArrowLeftRight,
  loan: Landmark,
  fuel: Fuel,
  phone: Smartphone,
  wifi: Wifi,
  coffee: Coffee,
  pet: PawPrint,
  baby: Baby,
  fitness: Dumbbell,
  tag: Tag,
}

/** The icon for a transaction's category (see categoryIconKey for the mapping). */
export function CategoryIcon({ category, type, ...props }: { category: string | null | undefined; type?: string } & LucideProps) {
  const Icon = ICONS[categoryIconKey(category, type)]
  return <Icon aria-hidden="true" {...props} />
}
